package datanormalizationtool;

import java.util.Map;
import java.util.HashMap;

/**
 * A mapping of all Massachusetts towns to their town code.
 */
public class TownCodeMappings {
  
  /**
   * Check if code is a valid town code. 
   * @param code town code to validate.
   * @return true if town code is valid.
   */
  public static final boolean isTownCode(String code) {
    return TOWN_CODE_MAP.containsValue(code.toLowerCase());
  }
  
  /**
   * Check if name is a valid town name.
   * @param name town name to validate.
   * @return true if town name is valid.
   */
  public static final boolean isTownName(String name) {
    return TOWN_CODE_MAP.containsKey(name.toLowerCase());
  }
  
  /**
   * Maps town name to it's town code.
   * @param name name of town to map to town code.
   * @return town code.
   */
  public static final String getTownCode(String name) {
    return TOWN_CODE_MAP.get(name.toLowerCase());
  }
  
  private static final Map<String, String> TOWN_CODE_MAP;
  static {
    TOWN_CODE_MAP = new HashMap<String, String>();
    TOWN_CODE_MAP.put("abington", "001");
    TOWN_CODE_MAP.put("acton", "002");
    TOWN_CODE_MAP.put("acushnet", "003");
    TOWN_CODE_MAP.put("adams", "004");
    TOWN_CODE_MAP.put("agawam", "005");
    TOWN_CODE_MAP.put("alford", "006");
    TOWN_CODE_MAP.put("amesbury", "007");
    TOWN_CODE_MAP.put("amherst", "008");
    TOWN_CODE_MAP.put("andover", "009");
    TOWN_CODE_MAP.put("arlington", "010");
    TOWN_CODE_MAP.put("ashburnham", "011");
    TOWN_CODE_MAP.put("ashby", "012");
    TOWN_CODE_MAP.put("ashfield", "013");
    TOWN_CODE_MAP.put("ashland", "014");
    TOWN_CODE_MAP.put("athol", "015");
    TOWN_CODE_MAP.put("attleboro", "016");
    TOWN_CODE_MAP.put("auburn", "017");
    TOWN_CODE_MAP.put("avon", "018");
    TOWN_CODE_MAP.put("ayer", "019");
    TOWN_CODE_MAP.put("barnstable", "020");
    TOWN_CODE_MAP.put("barre", "021");
    TOWN_CODE_MAP.put("becket", "022");
    TOWN_CODE_MAP.put("bedford", "023");
    TOWN_CODE_MAP.put("belchertown", "024");
    TOWN_CODE_MAP.put("bellingham", "025");
    TOWN_CODE_MAP.put("belmont", "026");
    TOWN_CODE_MAP.put("berkley", "027");
    TOWN_CODE_MAP.put("berlin", "028");
    TOWN_CODE_MAP.put("bernardston", "029");
    TOWN_CODE_MAP.put("beverly", "030");
    TOWN_CODE_MAP.put("billerica", "031");
    TOWN_CODE_MAP.put("blackstone", "032");
    TOWN_CODE_MAP.put("blandford", "033");
    TOWN_CODE_MAP.put("bolton", "034");
    TOWN_CODE_MAP.put("boston", "035");
    TOWN_CODE_MAP.put("bourne", "036");
    TOWN_CODE_MAP.put("boxborough", "037");
    TOWN_CODE_MAP.put("boxford", "038");
    TOWN_CODE_MAP.put("boylston", "039");
    TOWN_CODE_MAP.put("braintree", "040");
    TOWN_CODE_MAP.put("brewster", "041");
    TOWN_CODE_MAP.put("bridgewater", "042");
    TOWN_CODE_MAP.put("brimfield", "043");
    TOWN_CODE_MAP.put("brockton", "044");
    TOWN_CODE_MAP.put("brookfield", "045");
    TOWN_CODE_MAP.put("brookline", "046");
    TOWN_CODE_MAP.put("buckland", "047");
    TOWN_CODE_MAP.put("burlington", "048");
    TOWN_CODE_MAP.put("cambridge", "049");
    TOWN_CODE_MAP.put("canton", "050");
    TOWN_CODE_MAP.put("carlisle", "051");
    TOWN_CODE_MAP.put("carver", "052");
    TOWN_CODE_MAP.put("charlemont", "053");
    TOWN_CODE_MAP.put("charlton", "054");
    TOWN_CODE_MAP.put("chatham", "055");
    TOWN_CODE_MAP.put("chelmsford", "056");
    TOWN_CODE_MAP.put("chelsea", "057");
    TOWN_CODE_MAP.put("cheshire", "058");
    TOWN_CODE_MAP.put("chester", "059");
    TOWN_CODE_MAP.put("chesterfield", "060");
    TOWN_CODE_MAP.put("chicopee", "061");
    TOWN_CODE_MAP.put("chilmark", "062");
    TOWN_CODE_MAP.put("clarksburg", "063");
    TOWN_CODE_MAP.put("clinton", "064");
    TOWN_CODE_MAP.put("cohasset", "065");
    TOWN_CODE_MAP.put("colrain", "066");
    TOWN_CODE_MAP.put("concord", "067");
    TOWN_CODE_MAP.put("conway", "068");
    TOWN_CODE_MAP.put("cummington", "069");
    TOWN_CODE_MAP.put("dalton", "070");
    TOWN_CODE_MAP.put("danvers", "071");
    TOWN_CODE_MAP.put("dartmouth", "072");
    TOWN_CODE_MAP.put("dedham", "073");
    TOWN_CODE_MAP.put("deerfield", "074");
    TOWN_CODE_MAP.put("dennis", "075");
    TOWN_CODE_MAP.put("dighton", "076");
    TOWN_CODE_MAP.put("douglas", "077");
    TOWN_CODE_MAP.put("dover", "078");
    TOWN_CODE_MAP.put("dracut", "079");
    TOWN_CODE_MAP.put("dudley", "080");
    TOWN_CODE_MAP.put("dunstable", "081");
    TOWN_CODE_MAP.put("duxbury", "082");
    TOWN_CODE_MAP.put("east bridgewater", "083");
    TOWN_CODE_MAP.put("east brookfield", "084");
    TOWN_CODE_MAP.put("eastham", "085");
    TOWN_CODE_MAP.put("easthampton", "086");
    TOWN_CODE_MAP.put("east longmeadow", "087");
    TOWN_CODE_MAP.put("easton", "088");
    TOWN_CODE_MAP.put("edgartown", "089");
    TOWN_CODE_MAP.put("egremont", "090");
    TOWN_CODE_MAP.put("erving", "091");
    TOWN_CODE_MAP.put("essex", "092");
    TOWN_CODE_MAP.put("everett", "093");
    TOWN_CODE_MAP.put("fairhaven", "094");
    TOWN_CODE_MAP.put("fall river", "095");
    TOWN_CODE_MAP.put("falmouth", "096");
    TOWN_CODE_MAP.put("fitchburg", "097");
    TOWN_CODE_MAP.put("florida", "098");
    TOWN_CODE_MAP.put("foxborough", "099");
    TOWN_CODE_MAP.put("framingham", "100");
    TOWN_CODE_MAP.put("franklin", "101");
    TOWN_CODE_MAP.put("freetown", "102");
    TOWN_CODE_MAP.put("gardner", "103");
    TOWN_CODE_MAP.put("aquinnah", "104");
    TOWN_CODE_MAP.put("georgetown", "105");
    TOWN_CODE_MAP.put("gill", "106");
    TOWN_CODE_MAP.put("gloucester", "107");
    TOWN_CODE_MAP.put("goshen", "108");
    TOWN_CODE_MAP.put("gosnold", "109");
    TOWN_CODE_MAP.put("grafton", "110");
    TOWN_CODE_MAP.put("granby", "111");
    TOWN_CODE_MAP.put("granville", "112");
    TOWN_CODE_MAP.put("great barrington", "113");
    TOWN_CODE_MAP.put("greenfield", "114");
    TOWN_CODE_MAP.put("groton", "115");
    TOWN_CODE_MAP.put("groveland", "116");
    TOWN_CODE_MAP.put("hadley", "117");
    TOWN_CODE_MAP.put("halifax", "118");
    TOWN_CODE_MAP.put("hamilton", "119");
    TOWN_CODE_MAP.put("hampden", "120");
    TOWN_CODE_MAP.put("hancock", "121");
    TOWN_CODE_MAP.put("hanover", "122");
    TOWN_CODE_MAP.put("hanson", "123");
    TOWN_CODE_MAP.put("hardwick", "124");
    TOWN_CODE_MAP.put("harvard", "125");
    TOWN_CODE_MAP.put("harwich", "126");
    TOWN_CODE_MAP.put("hatfield", "127");
    TOWN_CODE_MAP.put("haverhill", "128");
    TOWN_CODE_MAP.put("hawley", "129");
    TOWN_CODE_MAP.put("heath", "130");
    TOWN_CODE_MAP.put("hingham", "131");
    TOWN_CODE_MAP.put("hinsdale", "132");
    TOWN_CODE_MAP.put("holbrook", "133");
    TOWN_CODE_MAP.put("holden", "134");
    TOWN_CODE_MAP.put("holland", "135");
    TOWN_CODE_MAP.put("holliston", "136");
    TOWN_CODE_MAP.put("holyoke", "137");
    TOWN_CODE_MAP.put("hopedale", "138");
    TOWN_CODE_MAP.put("hopkinton", "139");
    TOWN_CODE_MAP.put("hubbardston", "140");
    TOWN_CODE_MAP.put("hudson", "141");
    TOWN_CODE_MAP.put("hull", "142");
    TOWN_CODE_MAP.put("huntington", "143");
    TOWN_CODE_MAP.put("ipswich", "144");
    TOWN_CODE_MAP.put("kingston", "145");
    TOWN_CODE_MAP.put("lakeville", "146");
    TOWN_CODE_MAP.put("lancaster", "147");
    TOWN_CODE_MAP.put("lanesborough", "148");
    TOWN_CODE_MAP.put("lawrence", "149");
    TOWN_CODE_MAP.put("lee", "150");
    TOWN_CODE_MAP.put("leicester", "151");
    TOWN_CODE_MAP.put("lenox", "152");
    TOWN_CODE_MAP.put("leominster", "153");
    TOWN_CODE_MAP.put("leverett", "154");
    TOWN_CODE_MAP.put("lexington", "155");
    TOWN_CODE_MAP.put("leyden", "156");
    TOWN_CODE_MAP.put("lincoln", "157");
    TOWN_CODE_MAP.put("littleton", "158");
    TOWN_CODE_MAP.put("longmeadow", "159");
    TOWN_CODE_MAP.put("lowell", "160");
    TOWN_CODE_MAP.put("ludlow", "161");
    TOWN_CODE_MAP.put("lunenburg", "162");
    TOWN_CODE_MAP.put("lynn", "163");
    TOWN_CODE_MAP.put("lynnfield", "164");
    TOWN_CODE_MAP.put("malden", "165");
    TOWN_CODE_MAP.put("manchester", "166");
    TOWN_CODE_MAP.put("mansfield", "167");
    TOWN_CODE_MAP.put("marblehead", "168");
    TOWN_CODE_MAP.put("marion", "169");
    TOWN_CODE_MAP.put("marlborough", "170");
    TOWN_CODE_MAP.put("marshfield", "171");
    TOWN_CODE_MAP.put("mashpee", "172");
    TOWN_CODE_MAP.put("mattapoisett", "173");
    TOWN_CODE_MAP.put("maynard", "174");
    TOWN_CODE_MAP.put("medfield", "175");
    TOWN_CODE_MAP.put("medford", "176");
    TOWN_CODE_MAP.put("medway", "177");
    TOWN_CODE_MAP.put("melrose", "178");
    TOWN_CODE_MAP.put("mendon", "179");
    TOWN_CODE_MAP.put("merrimac", "180");
    TOWN_CODE_MAP.put("methuen", "181");
    TOWN_CODE_MAP.put("middleborough", "182");
    TOWN_CODE_MAP.put("middlefield", "183");
    TOWN_CODE_MAP.put("middleton", "184");
    TOWN_CODE_MAP.put("milford", "185");
    TOWN_CODE_MAP.put("millbury", "186");
    TOWN_CODE_MAP.put("millis", "187");
    TOWN_CODE_MAP.put("millville", "188");
    TOWN_CODE_MAP.put("milton", "189");
    TOWN_CODE_MAP.put("monroe", "190");
    TOWN_CODE_MAP.put("monson", "191");
    TOWN_CODE_MAP.put("montague", "192");
    TOWN_CODE_MAP.put("monterey", "193");
    TOWN_CODE_MAP.put("montgomery", "194");
    TOWN_CODE_MAP.put("mount washington", "195");
    TOWN_CODE_MAP.put("nahant", "196");
    TOWN_CODE_MAP.put("nantucket", "197");
    TOWN_CODE_MAP.put("natick", "198");
    TOWN_CODE_MAP.put("needham", "199");
    TOWN_CODE_MAP.put("new ashford", "200");
    TOWN_CODE_MAP.put("new bedford", "201");
    TOWN_CODE_MAP.put("new braintree", "202");
    TOWN_CODE_MAP.put("newbury", "203");
    TOWN_CODE_MAP.put("newburyport", "204");
    TOWN_CODE_MAP.put("new marlborough", "205");
    TOWN_CODE_MAP.put("new salem", "206");
    TOWN_CODE_MAP.put("newton", "207");
    TOWN_CODE_MAP.put("norfolk", "208");
    TOWN_CODE_MAP.put("north adams", "209");
    TOWN_CODE_MAP.put("northampton", "210");
    TOWN_CODE_MAP.put("north andover", "211");
    TOWN_CODE_MAP.put("north attleborough", "212");
    TOWN_CODE_MAP.put("northborough", "213");
    TOWN_CODE_MAP.put("northbridge", "214");
    TOWN_CODE_MAP.put("north brookfield", "215");
    TOWN_CODE_MAP.put("northfield", "216");
    TOWN_CODE_MAP.put("north reading", "217");
    TOWN_CODE_MAP.put("norton", "218");
    TOWN_CODE_MAP.put("norwell", "219");
    TOWN_CODE_MAP.put("norwood", "220");
    TOWN_CODE_MAP.put("oak bluffs", "221");
    TOWN_CODE_MAP.put("oakham", "222");
    TOWN_CODE_MAP.put("orange", "223");
    TOWN_CODE_MAP.put("orleans", "224");
    TOWN_CODE_MAP.put("otis", "225");
    TOWN_CODE_MAP.put("oxford", "226");
    TOWN_CODE_MAP.put("palmer", "227");
    TOWN_CODE_MAP.put("paxton", "228");
    TOWN_CODE_MAP.put("peabody", "229");
    TOWN_CODE_MAP.put("pelham", "230");
    TOWN_CODE_MAP.put("pembroke", "231");
    TOWN_CODE_MAP.put("pepperell", "232");
    TOWN_CODE_MAP.put("peru", "233");
    TOWN_CODE_MAP.put("petersham", "234");
    TOWN_CODE_MAP.put("phillipston", "235");
    TOWN_CODE_MAP.put("pittsfield", "236");
    TOWN_CODE_MAP.put("plainfield", "237");
    TOWN_CODE_MAP.put("plainville", "238");
    TOWN_CODE_MAP.put("plymouth", "239");
    TOWN_CODE_MAP.put("plympton", "240");
    TOWN_CODE_MAP.put("princeton", "241");
    TOWN_CODE_MAP.put("provincetown", "242");
    TOWN_CODE_MAP.put("quincy", "243");
    TOWN_CODE_MAP.put("randolph", "244");
    TOWN_CODE_MAP.put("raynham", "245");
    TOWN_CODE_MAP.put("reading", "246");
    TOWN_CODE_MAP.put("rehoboth", "247");
    TOWN_CODE_MAP.put("revere", "248");
    TOWN_CODE_MAP.put("richmond", "249");
    TOWN_CODE_MAP.put("rochester", "250");
    TOWN_CODE_MAP.put("rockland", "251");
    TOWN_CODE_MAP.put("rockport", "252");
    TOWN_CODE_MAP.put("rowe", "253");
    TOWN_CODE_MAP.put("rowley", "254");
    TOWN_CODE_MAP.put("royalston", "255");
    TOWN_CODE_MAP.put("russell", "256");
    TOWN_CODE_MAP.put("rutland", "257");
    TOWN_CODE_MAP.put("salem", "258");
    TOWN_CODE_MAP.put("salisbury", "259");
    TOWN_CODE_MAP.put("sandisfield", "260");
    TOWN_CODE_MAP.put("sandwich", "261");
    TOWN_CODE_MAP.put("saugus", "262");
    TOWN_CODE_MAP.put("savoy", "263");
    TOWN_CODE_MAP.put("scituate", "264");
    TOWN_CODE_MAP.put("seekonk", "265");
    TOWN_CODE_MAP.put("sharon", "266");
    TOWN_CODE_MAP.put("sheffield", "267");
    TOWN_CODE_MAP.put("shelburne", "268");
    TOWN_CODE_MAP.put("sherborn", "269");
    TOWN_CODE_MAP.put("shirley", "270");
    TOWN_CODE_MAP.put("shrewsbury", "271");
    TOWN_CODE_MAP.put("shutesbury", "272");
    TOWN_CODE_MAP.put("somerset", "273");
    TOWN_CODE_MAP.put("somerville", "274");
    TOWN_CODE_MAP.put("southampton", "275");
    TOWN_CODE_MAP.put("southborough", "276");
    TOWN_CODE_MAP.put("southbridge", "277");
    TOWN_CODE_MAP.put("south hadley", "278");
    TOWN_CODE_MAP.put("southwick", "279");
    TOWN_CODE_MAP.put("spencer", "280");
    TOWN_CODE_MAP.put("springfield", "281");
    TOWN_CODE_MAP.put("sterling", "282");
    TOWN_CODE_MAP.put("stockbridge", "283");
    TOWN_CODE_MAP.put("stoneham", "284");
    TOWN_CODE_MAP.put("stoughton", "285");
    TOWN_CODE_MAP.put("stow", "286");
    TOWN_CODE_MAP.put("sturbridge", "287");
    TOWN_CODE_MAP.put("sudbury", "288");
    TOWN_CODE_MAP.put("sunderland", "289");
    TOWN_CODE_MAP.put("sutton", "290");
    TOWN_CODE_MAP.put("swampscott", "291");
    TOWN_CODE_MAP.put("swansea", "292");
    TOWN_CODE_MAP.put("taunton", "293");
    TOWN_CODE_MAP.put("templeton", "294");
    TOWN_CODE_MAP.put("tewksbury", "295");
    TOWN_CODE_MAP.put("tisbury", "296");
    TOWN_CODE_MAP.put("tolland", "297");
    TOWN_CODE_MAP.put("topsfield", "298");
    TOWN_CODE_MAP.put("townsend", "299");
    TOWN_CODE_MAP.put("truro", "300");
    TOWN_CODE_MAP.put("tyngsborough", "301");
    TOWN_CODE_MAP.put("tyringham", "302");
    TOWN_CODE_MAP.put("upton", "303");
    TOWN_CODE_MAP.put("uxbridge", "304");
    TOWN_CODE_MAP.put("wakefield", "305");
    TOWN_CODE_MAP.put("wales", "306");
    TOWN_CODE_MAP.put("walpole", "307");
    TOWN_CODE_MAP.put("waltham", "308");
    TOWN_CODE_MAP.put("ware", "309");
    TOWN_CODE_MAP.put("wareham", "310");
    TOWN_CODE_MAP.put("warren", "311");
    TOWN_CODE_MAP.put("warwick", "312");
    TOWN_CODE_MAP.put("washington", "313");
    TOWN_CODE_MAP.put("watertown", "314");
    TOWN_CODE_MAP.put("wayland", "315");
    TOWN_CODE_MAP.put("webster", "316");
    TOWN_CODE_MAP.put("wellesley", "317");
    TOWN_CODE_MAP.put("wellfleet", "318");
    TOWN_CODE_MAP.put("wendell", "319");
    TOWN_CODE_MAP.put("wenham", "320");
    TOWN_CODE_MAP.put("westborough", "321");
    TOWN_CODE_MAP.put("west boylston", "322");
    TOWN_CODE_MAP.put("west bridgewater", "323");
    TOWN_CODE_MAP.put("west brookfield", "324");
    TOWN_CODE_MAP.put("westfield", "325");
    TOWN_CODE_MAP.put("westford", "326");
    TOWN_CODE_MAP.put("westhampton", "327");
    TOWN_CODE_MAP.put("westminster", "328");
    TOWN_CODE_MAP.put("west newbury", "329");
    TOWN_CODE_MAP.put("weston", "330");
    TOWN_CODE_MAP.put("westport", "331");
    TOWN_CODE_MAP.put("west springfield", "332");
    TOWN_CODE_MAP.put("west stockbridge", "333");
    TOWN_CODE_MAP.put("west tisbury", "334");
    TOWN_CODE_MAP.put("westwood", "335");
    TOWN_CODE_MAP.put("weymouth", "336");
    TOWN_CODE_MAP.put("whately", "337");
    TOWN_CODE_MAP.put("whitman", "338");
    TOWN_CODE_MAP.put("wilbraham", "339");
    TOWN_CODE_MAP.put("williamsburg", "340");
    TOWN_CODE_MAP.put("williamstown", "341");
    TOWN_CODE_MAP.put("wilmington", "342");
    TOWN_CODE_MAP.put("winchendon", "343");
    TOWN_CODE_MAP.put("winchester", "344");
    TOWN_CODE_MAP.put("windsor", "345");
    TOWN_CODE_MAP.put("winthrop", "346");
    TOWN_CODE_MAP.put("woburn", "347");
    TOWN_CODE_MAP.put("worcester", "348");
    TOWN_CODE_MAP.put("worthington", "349");
    TOWN_CODE_MAP.put("wrentham", "350");
    TOWN_CODE_MAP.put("yarmouth", "351");
    TOWN_CODE_MAP.put("devens", "352");
    TOWN_CODE_MAP.put("southfield", "353");
    TOWN_CODE_MAP.put("out of state", "888");
  }
}
